### ISSUE TITLE
The 404 Error Page is Broken

### ISSUE THREAD

**Issue by jilakav259** [MachineGunnur/GOG-Games#108]
http://goggamespc7v6z5e.onion.ws/game/bug
`Fatal error: Uncaught Error: Call to a member function modify() on boolean in /usr/share/nginx/html/web/index.php:142 Stack trace: #0 /usr/share/nginx/html/web/index.php(790): getGame('', '172.18.0.7') #1 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #2 /usr/share/nginx/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #3 /usr/share/nginx/html/vendor/slim/slim/Slim/Route.php(325): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #4 /usr/share/nginx/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(114): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #5 /usr/share/nginx/html/vendor/slim/slim/Slim/Route.php(297): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #6 /usr/share/nginx/html/vendor/slim/slim/Slim/ in /usr/share/nginx/html/web/index.php on line 142`

**Comment by MachineGunnur** [comment]
the orginial GOD team forgot api endpoint for not found game, why this happen!
